/**
 * AUTO-GENERATED FILE - Do not edit manually.
 * Generated by scripts/generate-active-blog-slugs.mjs.
 *
 * Derived from content/blog/*.md at build time so middleware stays in sync
 * with sitemap-blog.xml and the blog route's generateStaticParams().
 */

export const ACTIVE_BLOG_SLUGS: string[] = [
  "airpods-pro-2-cheapest-us-sg-my-jp",
  "amazon-prime-day-2026-preview",
  "best-gaming-laptops-us-2026",
  "best-laptop-deals-singapore",
  "best-laptop-deals-singapore-june-2026",
  "best-laptop-deals-under-sgd-2000-singapore",
  "best-noise-cancelling-headphones-2026-bose-sony-sennheiser-apple",
  "best-price-tracking-tools-singapore",
  "best-robot-vacuums-2026-pricing-compared",
  "best-time-to-buy-back-to-school-laptops-2026",
  "best-time-to-buy-cameras",
  "best-time-to-buy-electronics",
  "best-time-to-buy-fitness-tech",
  "best-time-to-buy-headphones",
  "best-time-to-buy-laptops",
  "best-time-to-buy-small-kitchen-appliances-2026",
  "best-time-to-buy-smartphones",
  "best-time-to-buy-smartwatches",
  "best-time-to-buy-tvs",
  "build-shopping-agent-buywhere-mcp",
  "building-production-mcp-servers",
  "buywhere-cursor-plugin-launch",
  "buywhere-mcp-goes-live",
  "buywhere-mcp-tools-cheatsheet",
  "buywhere-vs-google-shopping-vs-amazon-pricing-2026",
  "cheapest-iphone-17-singapore-june-2026",
  "cheapest-iphone-singapore-2026",
  "cheapest-macbook-air-m3-12-countries-compared",
  "cite-buywhere-catalog-stats-faq",
  "cite-buywhere-live-stats",
  "compare-headphones-singapore-2026",
  "compare-product-prices-singapore-2026",
  "fathers-day-deals-2026",
  "five-mcp-servers-that-earn-context-window",
  "home-appliance-deals-singapore-2026",
  "iphone-16-vs-iphone-17-upgrade-worth-it-2026",
  "mcp-for-ecommerce",
  "mcp-server-ecosystem-2026",
  "the-mcp-server-discovery-gap",
  "true-zero-human-self-serve-mcp-2026",
];
