-- BUY-73521: shopping_job_id purchase-job funnel instrumentation
-- See: https://paperclip.richteo.com/issues/BUY-73521
--
-- PURPOSE
-- Track the purchase-job funnel: job -> resolved product -> executable offer -> outbound link.
-- This replaces raw request volume as the north-star metric.
--
-- FUNNEL STAGES (ordered milestones with timestamps):
--   1. job_created    — first buyer-intent call accepted
--   2. product_resolved — at least one concrete BuyWhere product id returned
--   3. executable_offer_found — offer has merchant, price, deliverability, outbound URL
--   4. outbound_link_returned — response includes usable merchant/deal link
--
-- MINIMUM FIELDS:
--   shopping_job_id (UUID/ULID, stable across calls)
--   api_key_hash (sha256[:16], never raw secret)
--   tool_or_endpoint
--   deliver_to
--   country_code (after normalization)
--   query or product_id
--   product_id (where resolved)
--   merchant_id / merchant_name
--   offer_url_present (boolean)
--   is_internal (boolean, internal probes excluded from north-star)

BEGIN;

-- ---------------------------------------------------------------------------
-- monitoring.shopping_job_funnel
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS monitoring.shopping_job_funnel (
    id                  BIGSERIAL    PRIMARY KEY,
    shopping_job_id     UUID         NOT NULL,
    funnel_stage        TEXT         NOT NULL,          -- job_created | product_resolved | executable_offer_found | outbound_link_returned
    tool_name           TEXT         NOT NULL,          -- which tool created this stage
    api_key_hash        TEXT         NULL,              -- sha256(api_key)[:16] for cardinality
    deliver_to          TEXT         NOT NULL,          -- buyer market (ISO country code)
    country_code        TEXT         NULL,              -- normalized country from request
    query_text          TEXT         NULL,              -- search query (redacted if needed)
    product_id          TEXT         NULL,              -- resolved product id (products.id is BIGINT returned as string)
    merchant_id         TEXT         NULL,              -- merchant identifier
    merchant_name       TEXT         NULL,              -- merchant display name
    offer_url_present   BOOLEAN      NOT NULL DEFAULT false,
    is_internal         BOOLEAN      NOT NULL DEFAULT false,  -- internal probe flag
    is_replay           BOOLEAN      NOT NULL DEFAULT false,  -- continuation of existing job
    stage_data          JSONB        NULL,              -- extra stage-specific data
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_shopping_job_stage UNIQUE (shopping_job_id, funnel_stage)
);

-- Indexes for funnel aggregation queries
CREATE INDEX IF NOT EXISTS idx_shopping_job_funnel_job_id
    ON monitoring.shopping_job_funnel (shopping_job_id);
CREATE INDEX IF NOT EXISTS idx_shopping_job_funnel_deliver_to
    ON monitoring.shopping_job_funnel (deliver_to, created_at);
CREATE INDEX IF NOT EXISTS idx_shopping_job_funnel_tool
    ON monitoring.shopping_job_funnel (tool_name, created_at);
CREATE INDEX IF NOT EXISTS idx_shopping_job_funnel_is_internal
    ON monitoring.shopping_job_funnel (is_internal, created_at);
CREATE INDEX IF NOT EXISTS idx_shopping_job_funnel_stage
    ON monitoring.shopping_job_funnel (funnel_stage, created_at);

COMMENT ON TABLE monitoring.shopping_job_funnel IS
    'BUY-73521: purchase-job funnel tracking. One row per funnel stage milestone. Aggregation views compute: job_to_product_rate, product_to_offer_rate, offer_to_outbound_rate, end_to_end_purchase_job_success.';

COMMENT ON COLUMN monitoring.shopping_job_funnel.shopping_job_id IS
    'UUID stable across calls in the same purchase flow. Generated by client or server-minted.';

COMMENT ON COLUMN monitoring.shopping_job_funnel.funnel_stage IS
    'One of: job_created, product_resolved, executable_offer_found, outbound_link_returned. Ordered by created_at.';

COMMENT ON COLUMN monitoring.shopping_job_funnel.is_internal IS
    'True for internal health/probe traffic. Excluded from north-star conversion metrics (product sign-off requires external-only).';

COMMENT ON COLUMN monitoring.shopping_job_funnel.is_replay IS
    'True if this call continues an existing shopping_job_id (client-supplied). False for new job creation.';

-- ---------------------------------------------------------------------------
-- monitoring.shopping_job_funnel_daily (aggregation view)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW monitoring.shopping_job_funnel_daily AS
SELECT
    date_trunc('day', created_at AT TIME ZONE 'UTC')::date AS day,
    deliver_to,
    tool_name,
    is_internal,

    -- Funnel counts
    COUNT(*) FILTER (WHERE funnel_stage = 'job_created') AS jobs_created,
    COUNT(*) FILTER (WHERE funnel_stage = 'product_resolved') AS products_resolved,
    COUNT(*) FILTER (WHERE funnel_stage = 'executable_offer_found') AS offers_found,
    COUNT(*) FILTER (WHERE funnel_stage = 'outbound_link_returned') AS outbound_returned,

    -- Conversion rates (external only)
    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'product_resolved')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'job_created'), 0), 4
    ) AS job_to_product_rate,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'executable_offer_found')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'product_resolved'), 0), 4
    ) AS product_to_offer_rate,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'outbound_link_returned')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'executable_offer_found'), 0), 4
    ) AS offer_to_outbound_rate,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'outbound_link_returned')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'job_created'), 0), 4
    ) AS end_to_end_success_rate,

    -- Cardinality
    COUNT(DISTINCT shopping_job_id) AS distinct_jobs,
    COUNT(DISTINCT api_key_hash) AS distinct_api_keys,
    COUNT(DISTINCT product_id) AS distinct_products

FROM monitoring.shopping_job_funnel
GROUP BY 1, 2, 3, 4;

COMMENT ON VIEW monitoring.shopping_job_funnel_daily IS
    'BUY-73521: daily funnel metrics by deliver_to, tool, internal/external split. Denominator zero returns NULL (reported as insufficient_traffic).';

-- ---------------------------------------------------------------------------
-- monitoring.shopping_job_funnel_weekly (7-day rolling)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW monitoring.shopping_job_funnel_weekly AS
SELECT
    date_trunc('week', created_at AT TIME ZONE 'UTC')::date AS week_start,
    deliver_to,
    tool_name,
    is_internal,

    COUNT(*) FILTER (WHERE funnel_stage = 'job_created') AS jobs_created,
    COUNT(*) FILTER (WHERE funnel_stage = 'product_resolved') AS products_resolved,
    COUNT(*) FILTER (WHERE funnel_stage = 'executable_offer_found') AS offers_found,
    COUNT(*) FILTER (WHERE funnel_stage = 'outbound_link_returned') AS outbound_returned,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'product_resolved')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'job_created'), 0), 4
    ) AS job_to_product_rate,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'executable_offer_found')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'product_resolved'), 0), 4
    ) AS product_to_offer_rate,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'outbound_link_returned')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'executable_offer_found'), 0), 4
    ) AS offer_to_outbound_rate,

    ROUND(
        COUNT(*) FILTER (WHERE funnel_stage = 'outbound_link_returned')::numeric
        / NULLIF(COUNT(*) FILTER (WHERE funnel_stage = 'job_created'), 0), 4
    ) AS end_to_end_success_rate,

    COUNT(DISTINCT shopping_job_id) AS distinct_jobs,
    COUNT(DISTINCT api_key_hash) AS distinct_api_keys

FROM monitoring.shopping_job_funnel
WHERE created_at >= NOW() - INTERVAL '7 days'
GROUP BY 1, 2, 3, 4;

COMMENT ON VIEW monitoring.shopping_job_funnel_weekly IS
    'BUY-73521: 7-day rolling funnel metrics. Used for weekly product sign-off reports.';

COMMIT;
