-- BUY-71542: P2.6 emptiness_reason telemetry + v_ceo_kpis.silently_empty_rate
-- Catalog DB only.

-- Table to record every MCP empty 200 OK response for KPI analysis.
-- The "silently empty" metric is: empty responses in last 24h where emptiness_reason IS NULL.
CREATE TABLE IF NOT EXISTS monitoring.mcp_empty_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_name text NOT NULL,
  emptiness_reason text CHECK (emptiness_reason IN ('no_data', 'no_match', 'api_error', 'quota', 'region_unsupported', 'category_unsupported')),
  requested_country_code varchar(2),
  requested_category text,
  confidence text CHECK (confidence IN ('high', 'low')),
  response_time_ms integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mcp_empty_responses_tool_time
  ON monitoring.mcp_empty_responses (tool_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mcp_empty_responses_reason_time
  ON monitoring.mcp_empty_responses (emptiness_reason, created_at DESC);

-- Add silently_empty_rate to v_ceo_kpis.
-- silently_empty_rate = (empty responses with emptiness_reason IS NULL in last 24h) / (total empty responses in last 24h).
-- A non-null emptiness_reason means the API is correctly labeling why it's empty (good).
-- A null emptiness_reason means we don't know why it's empty (bad / "silently" empty).
CREATE OR REPLACE VIEW monitoring.v_ceo_kpis AS
WITH daily_sweeps AS (
  SELECT
    date_trunc('day', swept_at AT TIME ZONE 'UTC')::date AS day,
    AVG(near_miss_rate) AS daily_near_miss_rate
  FROM monitoring.sweep_results
  WHERE swept_at >= CURRENT_DATE - INTERVAL '7 days'
  GROUP BY 1
), seven_day AS (
  SELECT COALESCE(AVG(daily_near_miss_rate), 0::numeric) AS near_miss_rate
  FROM daily_sweeps
), latest_sweep AS (
  SELECT COALESCE(MAX(near_miss_rate), 0::numeric) AS max_near_miss_rate
  FROM monitoring.sweep_results
  WHERE sweep_id = (
    SELECT sweep_id
    FROM monitoring.sweep_results
    ORDER BY swept_at DESC
    LIMIT 1
  )
), empty_metrics AS (
  SELECT
    COUNT(*) FILTER (WHERE emptiness_reason IS NULL)::numeric /
      NULLIF(COUNT(*), 0) AS silently_empty_rate
  FROM monitoring.mcp_empty_responses
  WHERE created_at >= NOW() - INTERVAL '24 hours'
)
SELECT
  CURRENT_DATE AS report_date,
  COALESCE(empty_metrics.silently_empty_rate, 0) AS silently_empty_rate,
  seven_day.near_miss_rate,
  seven_day.near_miss_rate < 0.03 AS near_miss_7day_mean_under_threshold,
  latest_sweep.max_near_miss_rate < 0.04 AS near_miss_latest_sweep_under_threshold,
  CASE
    WHEN seven_day.near_miss_rate < 0.03 AND latest_sweep.max_near_miss_rate < 0.04 THEN 'healthy'::text
    WHEN seven_day.near_miss_rate < 0.05 THEN 'warning'::text
    ELSE 'critical'::text
  END AS p1_3_nm_status,
  now() AS computed_at
FROM seven_day, latest_sweep, empty_metrics;
