"""Affiliate click tracking redirect endpoint.

GET /v1/go/{tracking_id}?agent_id=<optional>
  - Logs the click to the `clicks` table (best-effort, non-blocking)
  - Redirects the user to the underlying affiliate URL

The tracking_id encodes product_id + platform in the format produced by
affiliate_links._generate_tracking_id().
"""
from __future__ import annotations

import asyncio
import logging
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, Query, Request
from fastapi.responses import RedirectResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.product import Click, Product
from sqlalchemy import select

from app.affiliate_links import (
    get_underlying_affiliate_url,
    parse_tracking_id,
)

logger = logging.getLogger("buywhere_api")

router = APIRouter()

_FALLBACK_URL = "https://buywhere.ai"


async def _record_click(
    db: AsyncSession,
    tracking_id: str,
    product_id: int,
    platform: str,
    destination_url: str,
    api_key_id: Optional[str],
    agent_id: Optional[str],
    user_agent: Optional[str],
    referrer: Optional[str],
) -> None:
    """Write a Click row (best-effort; errors are logged, not raised)."""
    try:
        click = Click(
            tracking_id=tracking_id,
            product_id=product_id,
            platform=platform,
            destination_url=destination_url,
            api_key_id=api_key_id,
            agent_id=agent_id,
            user_agent=user_agent[:500] if user_agent else None,
            referrer=referrer[:500] if referrer else None,
        )
        db.add(click)
        await db.commit()
    except Exception as exc:
        logger.warning(
            "click record failed: tracking_id=%s product_id=%s err=%s",
            tracking_id,
            product_id,
            exc,
        )
        try:
            await db.rollback()
        except Exception:
            pass


@router.get(
    "/v1/go/{tracking_id}",
    summary="Affiliate click-through redirect",
    response_class=RedirectResponse,
    tags=["affiliate"],
    include_in_schema=False,
)
async def click_redirect(
    tracking_id: str,
    request: Request,
    agent_id: Optional[str] = Query(None),
    db: AsyncSession = Depends(get_db),
) -> RedirectResponse:
    """Record an affiliate click and redirect to the merchant product page.

    This endpoint is used by tracked affiliate URLs generated by
    ``get_affiliate_url()`` when ``TRACKING_BASE_URL`` is set.
    """
    parsed = parse_tracking_id(tracking_id)
    if parsed is None:
        return RedirectResponse(url=_FALLBACK_URL, status_code=302)

    product_id, _digest = parsed

    # Resolve product URL + platform from DB
    destination_url: str = _FALLBACK_URL
    platform: str = "unknown"
    try:
        result = await db.execute(
            select(Product.url, Product.source).where(Product.id == product_id)
        )
        row = result.one_or_none()
        if row:
            raw_url: str = str(row.url or "")
            platform = str(row.source or "unknown")
            destination_url = get_underlying_affiliate_url(platform, raw_url) or raw_url or _FALLBACK_URL
    except Exception as exc:
        logger.warning("click_redirect product lookup failed: %s", exc)

    # Determine API key from request state (set by auth middleware if present)
    api_key_obj = getattr(request.state, "api_key", None)
    api_key_id: Optional[str] = str(getattr(api_key_obj, "id", "") or "") or None

    user_agent = request.headers.get("user-agent")
    referrer = request.headers.get("referer") or request.headers.get("referrer")

    # Deduplicated tracking_id: reuse provided tracking_id (already content-addressed)
    record_id = tracking_id

    # Fire-and-forget click record — don't hold up the redirect
    asyncio.create_task(
        _record_click(
            db=db,
            tracking_id=record_id,
            product_id=product_id,
            platform=platform,
            destination_url=destination_url,
            api_key_id=api_key_id,
            agent_id=agent_id,
            user_agent=user_agent,
            referrer=referrer,
        )
    )

    return RedirectResponse(url=destination_url, status_code=302)
