// MCP registry HTTP domain auth proof for buywhere.ai (BUY-5243)
// Proof generated by: mcp-publisher login http --domain buywhere.ai --private-key <ed25519-hex-key>
export function GET() {
  return new Response('v=MCPv1; k=ed25519; p=jRS8mUpBhfln2O7W456Z8Qnos1m21f6S+Cg25yS9/EU=', {
    headers: {
      'Content-Type': 'text/plain',
      'Cache-Control': 'public, max-age=86400',
    },
  });
}
