name: Read Production VM Host
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: write
jobs:
  read-host:
    name: Read host to artifact
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get host
        run: |
          echo -n "$HOST" > /tmp/host.txt
          echo -n "$USER" > /tmp/user.txt
          echo -n "22" > /tmp/port.txt
        env:
          HOST: ${{ secrets.PRODUCTION_DEPLOY_HOST }}
          USER: ${{ secrets.PRODUCTION_DEPLOY_USER }}
      - uses: actions/upload-artifact@v4
        with:
          name: vm-creds
          path: /tmp/*.txt
