name: Read SSH Key
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: write
jobs:
  read-key:
    name: Read SSH key to artifact
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get SSH key
        run: |
          echo -n "$KEY" > /tmp/ssh-key.txt
        env:
          KEY: ${{ secrets.PRODUCTION_DEPLOY_SSH_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: /tmp/ssh-key.txt
